clusterDomain: apps.live.cloud-platform.service.justice.gov.uk

image:
  repository: ""
  tag: oidc-mock-dab04b21a9749e60495f54316810bb98d900b75f

ingress:
  className: modsec-non-prod
  whitelistSourceRange: "35.178.209.113/32,3.8.51.207/32,35.177.252.54/32,10.200.0.0/20,35.176.127.232/32,35.177.145.193/32,18.130.39.94/32,128.77.75.64/26,51.149.250.0/24,51.149.249.0/29,194.33.249.0/29,51.149.249.32/29,194.33.248.0/29,20.49.214.199/32,20.49.214.228/32,20.26.11.71/32,20.26.11.108/32,51.149.251.0/24,51.149.249.64/29,1.149.249.0/29,194.33.192.0/25,194.33.196.0/25,18.169.147.172/32,35.176.93.186/32,18.130.148.126/32,35.176.148.126/32"
service:
  port: 9000

sabc:
  releaseName: ""
