server:
  tomcat:
    max-swallow-size: 500MB
  port: 8082


spring:
  servlet:
    multipart:
      max-file-size: ${SERVER_MAX_FILE_SIZE}
      max-request-size: ${SERVER_MAX_FILE_SIZE}
  security:
    oauth2:
      client:
        registration:
          silas-identity:
            client-id: ${SILAS_CLIENT_ID}
            client-secret: ${SILAS_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ${SILAS_SCOPE}
          moj-identity:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_CLIENT_SECRET}
            scope: ${AUTH_SCOPE}
            authorization-grant-type: client_credentials
        provider:
          silas-identity:
            # user-name-attribute: email
            issuer-uri: https://login.microsoftonline.com/${SILAS_TENANT_ID}/v2.0
          moj-identity:
            issuer-uri: https://login.microsoftonline.com/${AUTH_TENANT_ID}/v2.0
  threads:
    virtual:
      enabled: true
  http:
    client:
      factory: jdk
      connect-timeout: ${REST_CLIENT_CONNECT_TIMEOUT:5000}
      read-timeout: ${REST_CLIENT_READ_TIMEOUT:40000}
  session:
    store-type: redis

  data:
    redis:
      url: ${REDIS_HOST}

sds-api:
  url: ${SDS_API_URL}

claims-api:
  url: ${CLAIM_API_URL}
  accessToken: ${CLAIMS_API_ACCESS_TOKEN}

upload-max-file-size: ${UPLOAD_MAX_FILE_SIZE}

links:
  laa-homepage: https://www.gov.uk/government/organisations/legal-aid-agency
  bulk-upload-spreadsheet: https://assets.publishing.service.gov.uk/media/677bc6906f01ae28ab5c03ec/Provider_Bulkload_Spreadsheet.xls
  bulk-upload-spreadsheet-guide: https://assets.publishing.service.gov.uk/media/5a82c76aed915d74e623796e/bulkload-spreadsheet-guidance.pdf
  bulk-upload-guidance: https://www.gov.uk/guidance/submit-a-bulk-claim-sabc
  bulk-upload-amendments: https://www.gov.uk/guidance/submit-a-contracted-work-and-administration-cwa-claim-online#amendments-to-submitted-claims

management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
