server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: ${SERVER_MAX_FILE_SIZE}
      max-request-size: ${SERVER_MAX_FILE_SIZE}

  security:
    oauth2:
      client:
        registration:
          silas-identity:
            client-id: ${LASSIE_CLIENT_ID}
            client-secret: ${LASSIE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: ${LASSIE_SCOPE}
          moj-identity:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_CLIENT_SECRET}
            scope: ${AUTH_SCOPE}
            authorization-grant-type: client_credentials
        provider:
          silas-identity:
            issuer-uri: https://login.microsoftonline.com/${LASSIE_TENANT_ID}/v2.0
            user-name-attribute: email
          moj-identity:
            issuer-uri: https://login.microsoftonline.com/${AUTH_TENANT_ID}/v2.0
  http:
    client:
      factory: jdk
      connect-timeout: ${REST_CLIENT_CONNECT_TIMEOUT:5000}
      read-timeout: ${REST_CLIENT_READ_TIMEOUT:40000}

sds-api:
  url: ${SDS_API_URL}

cwa-api:
  url: ${CWA_API_URL}
  timeout: ${CWA_API_TIMEOUT}

upload-max-file-size: ${UPLOAD_MAX_FILE_SIZE}
