apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Release.Name }}-{{ .Release.Namespace }}-green
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: >
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-submit-a-bulk-claim"
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ if kindIs "slice" .Values.ingress.whitelistSourceRange }}{{ join "," .Values.ingress.whitelistSourceRange | quote }}{{ else }}{{ .Values.ingress.whitelistSourceRange | quote }}{{ end }}
spec:
  {{- $hostLabel := printf "%s-%s" .Release.Name .Release.Namespace | trunc 57 | trimSuffix "-" }}
  {{- $host := printf "%s.%s" $hostLabel .Values.clusterDomain }}
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ $host }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
