apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oidc-mock
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-oidc-mock
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
