apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-cwa-bulk-upload-deployment
  namespace: ${NAMESPACE}
  labels:
    app: laa-cwa-bulk-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-cwa-bulk-upload # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: laa-cwa-bulk-upload # this should match the selector in service.yml
    spec:
      containers:
        - name: laa-cwa-bulk-upload
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8082
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: AUTH_CLIENT_ID

            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: AUTH_CLIENT_SECRET

            - name: AUTH_CLOUD_INSTANCE
              value : https://login.microsoftonline.com

            - name: AUTH_SCOPE
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: AUTH_SCOPE

            - name: AUTH_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: AUTH_TENANT_ID

            - name: SDS_API_URL
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: SDS_API_URL

            - name: CWA_API_URL
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: CWA_API_URL

            - name: CWA_API_TIMEOUT
              valueFrom:
                secretKeyRef:
                  name: cwa-bulk-upload-secrets
                  key: CWA_API_TIMEOUT