name: Build main

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:

  build:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1.0.10
    permissions:
      contents: write
      packages: write
    with:
      integration_test_task: "integrationTest"
      create_tag: 'true'
      github_bot_username: 'laa-ccms-caab-service'
      semgrep_check: 'true'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'

  pact-test:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/pact-and-publish.yml@story/pact-publish
    permissions:
      contents: write
      packages: write
    with:
      pact_test_task: "pactTest"
      publish_pact_results: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      pact_broker_url: ${{ secrets.PACT_BROKER_URL }}
      pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}